version: '3.3'

services:

  app:
    restart: always
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - workspace_volume:/workspace
      - ../2048_Project/webgui/datasets:/workspace/2048_Project/webgui/datasets # Mounte Ordner für WebGUI Datasets
      - ../2048_Project/webgui/logs:/workspace/2048_Project/webgui/logs # Mounte Ordner für WebGUI Logs
      - ../2048_Project/webgui/datasets:/workspace/2048_Project/datasets # Mounte Ordner für Datasets
      - ../2048_Project/webgui/datasets:/workspace/2048_Project/saves # Mounte Ordner für Modelle
      - ../2048_Project/webgui/logs:/workspace/2048_Project/logs # Mounte Ordner für Main logs
      - ..:/workspace/Local # Erlaubt editieren des Projektes ausserhalb des Dockers
    ports:
      - 8282:8282
      - 8283:8283
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      - mysql
    working_dir: /workspace

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tool:
    image: phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on: 
      - mysql

volumes:
  mysql-data:
  workspace_volume:
